fix : old published news images not displayed for none mumbers - EXO-64578
exoplatform/data-upgrade pull request #156
Opened 2023-06-07 11:29 UTC by sofyenne

This change will update the permissions for displaying published news images to non-members.

2023-06-07 14:49 UTC, ahamdi requested changes

2023-06-07 14:49 UTC, ahamdi commented on data-upgrade-news/src/main/resources/conf/portal/configuration.xml
> +          <value>org.exoplatform.platform</value>
```suggestion
          <value>org.exoplatform.news</value>
```

2023-06-07 14:49 UTC, ahamdi commented on data-upgrade-news/src/main/resources/conf/portal/configuration.xml
> +        </value-param>
I am not sure if this UP will be reused, is there a need to parameterize those properties ?

2023-06-07 14:49 UTC, ahamdi commented on data-upgrade-news/src/main/resources/conf/portal/configuration.xml
> +          <value>6.5.x</value>
We should put an exact version here

2023-06-07 14:49 UTC, ahamdi commented on data-upgrade-news/src/main/java/org/exoplatform/news/upgrade/jcr/PublishedNewsImagesPermissionsUpgradePlugin.java
> +  public PublishedNewsImagesPermissionsUpgradePlugin(InitParams initParams, RepositoryService repositoryService, SessionProviderService sessionProviderService) {
Could you format this file correctly ?

2023-06-07 15:16 UTC, sofyenne commented on data-upgrade-news/src/main/resources/conf/portal/configuration.xml
> +          <value>org.exoplatform.platform</value>
done !

2023-06-07 15:16 UTC, sofyenne commented on data-upgrade-news/src/main/resources/conf/portal/configuration.xml
> +        </value-param>
done !

2023-06-07 15:16 UTC, sofyenne commented on data-upgrade-news/src/main/resources/conf/portal/configuration.xml
> +          <value>6.5.x</value>
done !

2023-06-07 15:16 UTC, sofyenne commented on data-upgrade-news/src/main/java/org/exoplatform/news/upgrade/jcr/PublishedNewsImagesPermissionsUpgradePlugin.java
> +  public PublishedNewsImagesPermissionsUpgradePlugin(InitParams initParams, RepositoryService repositoryService, SessionProviderService sessionProviderService) {
done !

2023-06-08 15:23 UTC, ahamdi approved these changes

2023-06-08 15:26 UTC, merged