fix: Configure the PortalNavigationIconUpgradePlugin to set icons to the portal navigation nodes - EXO-69848 (#209)
exoplatform/data-upgrade pull request #210
Opened 2024-03-07 15:26 UTC by sofyenne

Prior to this change after migrating from the 6.4 to the 6.5 then to the 6.6 version , the external stream node navigation icon was incorrect , this change is going to configure the PortalNavigationIconUpgradePlugin in order to set icons for the portal navigation nodes .

2024-03-07 17:18 UTC, azayati requested changes
@sofyenne have you tested that on pgsql ?

2024-03-08 14:25 UTC, sofyenne commented
> @sofyenne have you tested that on pgsql ?

Yep!

2024-03-08 14:31 UTC, azayati requested changes

2024-03-08 14:31 UTC, azayati commented on data-upgrade-navigations/src/test/java/org/exoplatform/migration/PortalNavigationIconMigrationTest.java
> +package org.exoplatform.migration;
put the header

2024-03-08 14:40 UTC, azayati approved these changes
LGTM

2024-03-08 14:41 UTC, Jihed525 approved these changes

2024-03-08 14:47 UTC, merged